config/routes.rb
GATest::Application.routes.draw do
  resources :properties
  resources :upload, only: [:new, :create]
  devise_for :users
  resources :accounts, only: [:index]
  get '/auth/:provider/callback', to: 'accounts#create'
  root :to => "accounts#index"
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_writer :access_token

  def refresh_access_token
    client = OAuth2::Client.new(ENV['GOOGLE_PUBLIC'], ENV['GOOGLE_PRIVATE'], site: 'https://accounts.google.com', authorize_url: '/o/oauth2/auth', token_url: '/o/oauth2/token')
    access_token = OAuth2::AccessToken.from_hash(client, refresh_token: self.refresh_token)
    @access_token = access_token.refresh!.token
  end

  def access_token
    @access_token || refresh_access_token
  end

  def client
    @client ||= refresh_client
  end

  def refresh_client
    client = Google::APIClient.new
    client.authorization.client_id = ENV['GOOGLE_PUBLIC']
    client.authorization.client_secret = ENV['GOOGLE_PRIVATE']
    client.authorization.refresh_token = self.refresh_token
    client.authorization.refresh!
    client
  end

  def analytics
    self.client.discovered_api('analytics', 'v3')
  end
end

app/models/instructions.rb
method in user model that makes API calls to retrieve accounts and build account models

result = client.execute()
accounts = result['data']['items']
account_numbers [{id: 123}, {id: 234}]
account_numbers.each do |n|
  Account.new(account_number: n)
end


def do_upload
    date = Time.now.strftime('%Y-%m-%d')
    media = Google::APIClient::UploadIO.new('public/data.csv', 'application/octet-stream')
    metadata = {
      'title'     => date,
      'mimeType'  => 'application/octet-stream',
      'resumable' => false
    }
    @client.execute(
      api_method: @analytics.management.daily_uploads.upload,
      parameters: { 'uploadType'          => 'multipart',
                    'appendNumber'        => 1,
                    'date'                => date,
                    'type'                => 'cost',
                    'accountId'           => '44706033',
                    'webPropertyId'       => 'UA-44706033-1',
                    'customDataSourceId'  => '7LwIbTS7R8m7kc_EFXjJzQ'
                  },
      media: media,
      body_object: metadata).inspect
  end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user

  validates :property_name, presence: true
  validates :ga_property_id, presence: true
  validates :custom_data_id, presence: true
end

app/models/source.rb
class Source < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_writer :access_token

  has_many :properties

  def refresh_access_token
    client = OAuth2::Client.new(ENV['GOOGLE_PUBLIC'], ENV['GOOGLE_PRIVATE'], site: 'https://accounts.google.com', authorize_url: '/o/oauth2/auth', token_url: '/o/oauth2/token')
    access_token = OAuth2::AccessToken.from_hash(client, refresh_token: self.refresh_token)
    @access_token = access_token.refresh!.token
  end

  def access_token
    @access_token || refresh_access_token
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def current_account
    Account.first
  end

  def index
    @account = Account.all
  end

  def create
    auth = env['omniauth.auth']
    credentials = auth['credentials']
    Account.create(access_token: credentials['token'], refresh_token: credentials['refresh_token'])
    redirect_to :accounts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    properties_path
  end
end

app/controllers/properties_controller.rb
require 'csv'

class PropertiesController < ApplicationController
  def index
    @properties = current_user.properties.all if current_user
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(properties_params)
    if @property.save
      flash[:notice] = "Property was saved."
      redirect_to @property
    else
      flash[:error] = "Property was not saved."
      render :new
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    @property.user_id = current_user.id
    if @property.update_attributes(properties_params)
      flash[:notice] = "Property was updated."
      redirect_to @property
    else
      flash[:error] = "Property was not updated."
      render :edit
    end
    CSV.new(params[:property][:data])
  end

  def show
    @property = Property.find(params[:id])
  end

  def destroy
    @property = Property.find(params[:id])
    if @property.destroy
      flash[:notice] = "Property deleted."
      redirect_to properties_path
    else
      flash[:error] = "There was a problem deleting the Property"
      render :show
    end
  end


def upload
  uploaded_io = params[:property][:data]
  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    file.write(uploaded_io.read)
  end
end

private
  
  def properties_params
    params.require(:property).permit(:property_name, :ga_property_id, :custom_data_id)
  end


end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def new
  end

  def create
    @source = Source.find(params[:source_id])
    @property = Property.find(params[:property_id])
    client = Google::APIClient.new
    client.authorization.access_token = Account.last.access_token
    analytics = client.discovered_api('analytics', 'v3')

    # file = StringIO.new(GoogleAnalytics::CSVConverter.new(params[:csv],@source.ga_source, @source.ga_medium).to_s)
    file = params[:csv]
    date = params[:date]
    accountId = @property.ga_property_id[/\d+/]
    webPropertyId = @property.ga_property_id
    customDataSourceId = @property.custom_data_id
    media = Google::APIClient::UploadIO.new(file, 'application/octet-stream')
    metadata = {
      'title'     => date,
      'mimeType'  => 'application/octet-stream',
      'resumable' => false
    }
   # raise accountId.class.inspect
    raise client.execute(
      api_method: analytics.management.daily_uploads.upload,
      parameters: { 'uploadType'          => 'multipart',
                    'appendNumber'        => 1,
                    'date'                => date,
                    'type'                => 'cost',
                    'accountId'           => accountId,
                    'webPropertyId'       => webPropertyId,
                    'customDataSourceId'  => customDataSourceId
                  },
      media: media,
      body_object: metadata).inspect
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/accounts/index.html.haml
%h1 All Accounts
= link_to "Auth with Google", '/auth/google_oauth2'
%table
  / %tr
  /   / %th Email
  /   %th Refresh Token
  / - @account.each do |account|
  /   %tr
  /     / %td= account.email
  /     %td= account.refresh_token

app/views/layouts/application.html.erb
<html>
  <head>
    <title>GATest</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-cloud-upload" id="cloud-upload"></span></a>
          <%= link_to "GA Cost Data Uploader", root_path, { class: "navbar-brand" } %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "View Properties", properties_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to current_user.email, "#" %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
 
    <div class="container">
      <div class="row">
        <div class="col-md-9"><%= yield %></div>
        <div class="col-md-3">
          <div class="page-header">
            <h2>About Us</h2>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            <!-- Small modal -->
            <button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small modal</button>

            <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  ...
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title GATest
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #user_nav
      - if user_signed_in?
        Logged in as
        %strong= current_user.email
        = link_to "Edit profile", edit_user_registration_path |
        = link_to "Logout", destroy_user_session_path, method: :delete
      - else
        = link_to "Sign up", new_user_registration_path
        = link_to "Login", new_user_session_path
    = yield

app/views/properties/_form.html.haml
= simple_form_for(@property, html: {class: 'form-group' }) do |f|
  /= f.error_messages
  = f.input :property_name, :placeholder => "Enter Property Name", :class => "form-control", :label => "Property Name"
  = f.input :ga_property_id, :placeholder => 'UA-XXXXXXX-XX', :label => "GA Property Id"
  = f.input :custom_data_id, :placeholder => "Alphanumeric String", :label => "Custom Data Upload Id"
  = f.button :submit, :class => "btn btn-primary"

app/views/properties/delete.html.haml
%h1 Properties#delete
%p Find me in app/views/properties/delete.html.haml

app/views/properties/edit.html.haml
.panel.panel-info
  .panel-heading
    .panel-title Edit Property
  .panel-body
    = render partial: 'form'
    = link_to "Delete Property", @property, {:method => :delete, :confirm => "Are you sure?", :class => 'btn btn-danger' }

app/views/properties/index.html.haml
.page-header
  %h1 Properties

- if current_user.nil?
  %p There's no Properties to list
  = link_to "Sign up", new_user_registration_path
  or
  = link_to "Login", new_user_session_path
- else
  - @properties.each do |p|
    .media
      .media-body
        %h4.media-heading
          .well.well-sm
            = link_to p.property_name, p
            = "(#{p.ga_property_id})"
    = link_to "New Property", new_property_path,  { :class => 'btn btn-success' }

app/views/properties/new.html.haml
.panel.panel-default
  .panel-heading
    .panel-title 
      %b Add a New GA Property
  .panel-body 
    = render partial: 'form'

app/views/properties/show.html.haml
/ .panel.panel-default
/   .panel-heading
/     .panel-title 
/       %b Property Name: 
/       = @property.property_name
/   .panel-body 
/     %p
/       %b GA Property Id: #{@property.ga_property_id}
/     %p
/       %b Custom Data Source Id: #{@property.custom_data_id}
/     %p
/       %b User Email: #{@property.user.email}
/     %p
/       = link_to "Edit Property", edit_property_path, :class => "btn btn-default"

.well
  %h4= @property.property_name
  %p
    %b GA Property Id: #{@property.ga_property_id}
  %p
    %b Custom Data Source Id: #{@property.custom_data_id}
  %p
    = link_to "Edit Property", edit_property_path, :class => "btn btn-default"

.panel.panel-default
  .panel-heading
    .panel-title 
      %b Upload File
  .panel-body 
    = render partial: '/upload/form', locals: {property: @property}

%button{"data toggle" => "modal", "data-target" => "#myModal", :class => "btn btn-primary btn-lg"} Modal Button

.modal.fade{"id" => "myModal", "role" => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button{"type" => "button", "class" => "close", "data-dismiss" => "modal", "aria-hidden" => "true"}
        .modal-title Modal Title
      .modal-body One Fine Body
      .modal-footer Footer}

app/views/upload/_form.html.haml
= form_tag upload_index_path, multipart: true do
  .row.form-group
    .col-md-6.col-xs-6
      = label_tag(nil, "File Input")
      = file_field_tag(:csv, type: "file", :class => "")
  .row.form-group
    .col-md-6.col-xs-6
      = label_tag(nil, "GA Property ID")
      = collection_select(nil, :property_id, Property.all, :id, :ga_property_id, {:selected => @property.id}, {:class => "form-control input-lg"})
  .row.form-group
    .col-md-6.col-xs-6
      = label_tag(nil, "Source Type")
      = collection_select(nil, :source_id, Source.all, :id, :name, {}, {:class => "form-control input-lg"})
  .row.form-group
    .col-md-6.col-xs-6
      = label_tag(nil, "Upload Data For")
      = date_field(nil, :date, type: "date", :class => "form-control input-lg")
  = submit_tag("Upload", :class => "btn btn-primary")

app/views/upload/create.html.haml
%h1 Upload#create
%p Find me in app/views/upload/create.html.haml

app/views/upload/new.html.haml
= render partial: 'form', locals: {property: @property}